title: Cinewise - A Movie Recommendation System
url : "https://ritviyer.github.io/BigData/"
theme: jekyll-theme-cayman
description: Anwika Bhandary, Meghana Deepak, Ritvik Iyer, Aditya Pansare, Rucha Sathe
